- hosts: server
  become: yes
  tasks:
    - name: read config variables
      include_vars: vars.yml
      # /vagrant path is used because ansible_local playbook runs inside virtual host
    - name: include provision_server.yml
      include_tasks: provision_server.yml
    # In VirtualBox on Windows files in shared /vagrant folder have too wide permissions
    # openssh refuses to use private keys with wrong mode
    - name: copy template ssh key to local directory and change its mode
      shell: cp -f /vagrant/.vagrant/machines/template/virtualbox/private_key /home/vagrant/template_private_key && chown vagrant /home/vagrant/template_private_key && chmod 0600 /home/vagrant/template_private_key
  handlers:
    - name: systemctl daemon-reload
      shell: systemctl daemon-reload
    - name: restart dnsmasq
      service: name=dnsmasq state=restarted
    - name: restart nginx
      service: name=nginx state=restarted

- hosts: template
  become: yes
  tasks:
  - name: read config variables
    include_vars: vars.yml
  - name: include provision_template.yml
    include_tasks: provision_template.yml
  - name: install GUI packages
    include_tasks: provision_template_gui.yml
    when: install_gui_and_rdp_client
  handlers:
    # update artifacts in build every time we need to regenerate initrd
    - name: update initramfs
      shell: update-initramfs -u && cd /vagrant && ./build.sh initrd
    - name: systemctl daemon-reload
      shell: systemctl daemon-reload
    - name: reload sshd
      service: name=sshd state=reloaded
