#!/bin/sh

PREREQ=""

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/atftp /bin
copy_exec /usr/bin/wget /bin
copy_exec /bin/tar /bin
copy_exec /bin/gunzip /bin

manual_add_modules squashfs
# Overlayfs
manual_add_modules overlay
# Fucking closed-source Intel(really it is PowerVR SGX) graphics with a lot of problems
#manual_add_modules cedarview_gfx
# Fallback is no better drivers
manual_add_modules uvesafb

exit 0
